[package]
name = "ample"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = "0.1.13"
cpal = { version = "0.17.0", default-features = false }
gil = "0.5.6"
iced = "0.14.0"
symphonia = { version = "0.5.5", default-features = false, features = ["mp3", "opt-simd"] }
thiserror = "2.0.17"
